<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Ingredient</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="p-4">
<h1>Add Ingredient</h1>
<form action="/addIngredientPage" method="post">
    <input type="text" name="name" placeholder="Ingredient name"><br>
    <input type="text" name="quantity" placeholder="Quantity"><br><br>
    <button type="submit">Add Ingredient</button>
</form>
</body>
</html>
`